### ISSUE TITLE
Migrating to MatrixOptInterface?

### ISSUE THREAD

**Issue by frapac** [exanauts/Simplex.jl#19]
Currently, we are using GLPK to import problems from MPS and build the corresponding matrix. 
I am wondering if we could use [MatrixOptInterface](https://github.com/jump-dev/MatrixOptInterface.jl) instead. That would allow to specify problems also with JuMP, by an appropriate use of `MOI.copy_to`.

**Comment by kibaekkim** [comment]
Yeah, it looks interesting. Is the package still making progress? I see it has not been released yet.

**Comment by frapac** [comment]
I would say there is increased interest in it. They are planning to incorporate it in this package: https://github.com/AKS1996/DiffOpt.jl/
Also, MatOI.jl could be very useful for all matrix-based solvers

**Comment by kibaekkim** [comment]
I see that the package implements what I just refactored... structures for LP forms. Yeah, this package must be pretty useful!

**Comment by kibaekkim** [comment]
@frapac can you see if we can move to this package?

**Comment by frapac** [comment]
I will investigate!
